sendTrainDelayToSlack:
  handler: src/models/lambda/trainDelay.sendToSlack
  events:
    - schedule: 
      ## 7:00,7:20,7:40,8:00,8:20,8:40,18:00,18:20,18:40 月~金 
      rate: cron(0,20,40 9,22,23 ? * MON-FRI *)
  layers:
      - {Ref: ChromeLambdaLayer}
  environment:
    TRAIN_DELAY_JSON_URL: 'https://tetsudo.rti-giken.jp/free/delay.json'
    SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/*************************'
